"""Separate-process CLI coverage for the V0.4 static-prop dry-run contract.

All concepts and providers in these tests are local fixtures. No Meshy or other
external generation API is called.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import sqlite3
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml
from PIL import Image

PROJECT = Path(__file__).resolve().parents[2]
FIXTURE = PROJECT / "examples" / "minimal-godot"
SPEC_FIXTURE = PROJECT / "src" / "gamefactory" / "resources" / "specs" / "prop_energy_crate_01.yml"
_STATE_TABLES = (
    "workflows",
    "tasks",
    "executions",
    "approvals",
    "artifacts",
    "evidences",
    "quality_gates",
    "provider_invocations",
    "asset_revisions",
    "provider_operation_intents",
    "audit_events",
)


def _cli(root: Path, *arguments: str) -> tuple[subprocess.CompletedProcess[str], Any]:
    env = os.environ.copy()
    existing = env.get("PYTHONPATH")
    env["PYTHONPATH"] = str(PROJECT / "src") + (os.pathsep + existing if existing else "")
    result = subprocess.run(
        [
            sys.executable,
            "-m",
            "gamefactory",
            "--json",
            "--project",
            str(root),
            *arguments,
        ],
        cwd=root,
        env=env,
        text=True,
        capture_output=True,
        check=False,
        timeout=60,
    )
    stream = result.stdout.strip() or result.stderr.strip()
    assert stream, f"CLI emitted no JSON; stdout={result.stdout!r}; stderr={result.stderr!r}"
    try:
        payload = json.loads(stream)
    except json.JSONDecodeError as exc:
        raise AssertionError(f"CLI did not emit JSON: {stream}") from exc
    return result, payload


def _prepare_project(root: Path) -> tuple[Path, Path, dict[str, Any]]:
    shutil.copytree(FIXTURE, root)
    init, initialized = _cli(root, "init")
    assert init.returncode == 0, initialized
    assert initialized["godot_project"] is True

    spec = yaml.safe_load(SPEC_FIXTURE.read_text(encoding="utf-8"))
    spec_path = root / "acceptance-spec.yml"
    spec_path.write_text(yaml.safe_dump(spec, sort_keys=False), encoding="utf-8")
    concept_path = root / "acceptance-concept.png"
    Image.new("RGB", (32, 32), (45, 108, 164)).save(concept_path, format="PNG")
    provenance_path = root / "acceptance-concept.provenance.json"
    provenance_path.write_text(
        json.dumps(
            {
                "sha256": hashlib.sha256(concept_path.read_bytes()).hexdigest(),
                "source_type": "synthetic_acceptance_fixture",
                "prompt": "Deterministic local fixture; not generated by an AI provider.",
                "generation": {"provider": "scripted_fixture", "paid": False},
            }
        ),
        encoding="utf-8",
    )
    return spec_path, concept_path, spec


def _state_snapshot(root: Path) -> dict[str, int]:
    db_path = root / ".gamefactory" / "state" / "factory.db"
    with sqlite3.connect(db_path) as connection:
        return {
            table: int(connection.execute(f"SELECT COUNT(*) FROM {table}").fetchone()[0])
            for table in _STATE_TABLES
        }


def _dry_run_arguments(
    spec_path: Path, concept_path: Path, provenance_path: Path
) -> tuple[str, ...]:
    return (
        "asset-create",
        "--spec",
        str(spec_path),
        "--concept",
        str(concept_path),
        "--provenance",
        str(provenance_path),
        "--concept-source-type",
        "imported",
        "--provider",
        "fake",
        "--dry-run",
    )


def test_asset_create_dry_run_describes_plan_without_mutating_workflow_state(
    tmp_path: Path,
) -> None:
    root = tmp_path / "game"
    spec_path, concept_path, spec = _prepare_project(root)
    provenance_path = root / "acceptance-concept.provenance.json"
    before = _state_snapshot(root)

    result, payload = _cli(root, *_dry_run_arguments(spec_path, concept_path, provenance_path))

    assert result.returncode == 0, payload
    assert payload["dry_run"] is True
    assert payload["workflow_state_mutated"] is False
    assert payload["api_requests"] == 0
    assert payload["paid_provider_invocations"] == 0
    assert payload["concept_sha256"] == hashlib.sha256(concept_path.read_bytes()).hexdigest()
    assert payload["specification"]["asset_id"] == spec["asset_id"]
    assert payload["specification"]["dimensions"] == spec["dimensions"]
    assert payload["concept_state"] == "VALIDATED_PENDING_HUMAN_APPROVAL"
    assert payload["required_approvals"] == [
        "concept_review",
        "paid_generation",
        "final_visual_review",
    ]
    assert payload["provider"] == "fake"
    assert payload["operation"] == "fake-image-to-3d"
    assert payload["estimated_cost"] == 5.0

    readiness = payload["readiness"]
    assert {"godot", "blender", "meshy_cli", "image_generation"} <= readiness.keys()
    assert readiness and all(isinstance(value, str) and value for value in readiness.values())
    steps = payload["expected_steps"]
    assert isinstance(steps, list) and len(steps) >= 6
    plan = " ".join(str(step).casefold() for step in steps)
    for expected in ("concept", "approval", "generation", "blender", "godot", "final"):
        assert expected in plan, f"pipeline plan omitted {expected}: {steps}"
    assert payload.get("status") != "COMPLETED"
    assert _state_snapshot(root) == before


def test_asset_create_dry_run_invalid_inputs_do_not_mutate_state(tmp_path: Path) -> None:
    root = tmp_path / "game"
    spec_path, concept_path, _spec = _prepare_project(root)
    provenance_path = root / "acceptance-concept.provenance.json"
    before = _state_snapshot(root)

    invalid_spec_path = root / "invalid-spec.yml"
    invalid_spec_path.write_text("schema_version: 0.0\nasset_id: broken\n", encoding="utf-8")
    invalid_spec, invalid_payload = _cli(
        root,
        *_dry_run_arguments(invalid_spec_path, concept_path, provenance_path),
    )
    assert invalid_spec.returncode != 0
    assert isinstance(invalid_payload, dict) and invalid_payload.get("error")
    assert _state_snapshot(root) == before

    missing_provenance = root / "does-not-exist.provenance.json"
    absent_sidecar, absent_payload = _cli(
        root,
        *_dry_run_arguments(spec_path, concept_path, missing_provenance),
    )
    assert absent_sidecar.returncode != 0
    assert isinstance(absent_payload, dict) and absent_payload.get("error")
    assert _state_snapshot(root) == before
