"""Windows path-length preflight for files generated by Blender adapters."""

from __future__ import annotations

import os
from collections.abc import Iterable
from pathlib import Path

from gamefactory.core.domain.errors import ValidationError

# MAX_PATH is 260 UTF-16 code units including the terminating NUL. An
# unprefixed absolute path can therefore contain at most 259 visible units.
MAX_WINDOWS_PATH_UTF16_UNITS = 259


def ensure_windows_output_paths(
    paths: Iterable[tuple[str, Path | str]], *, windows: bool | None = None
) -> None:
    """Reject planned filesystem paths that exceed legacy Windows MAX_PATH.

    ``windows`` is exposed for deterministic boundary tests. Production callers
    omit it, which preserves POSIX behavior and checks only on Windows.
    """
    is_windows = os.name == "nt" if windows is None else windows
    if not is_windows:
        return

    for label, path in paths:
        rendered = os.fspath(path)
        units = len(rendered.encode("utf-16-le", errors="surrogatepass")) // 2
        if units > MAX_WINDOWS_PATH_UTF16_UNITS:
            raise ValidationError(
                f"Planned {label} path is {units} UTF-16 code units; Windows supports at most "
                f"{MAX_WINDOWS_PATH_UTF16_UNITS} here. Shorten the project, workflow, or asset "
                "path and retry."
            )
